### ISSUE TITLE
Works in SP, but not MP

### ISSUE THREAD

**Issue by HootlingMC** [notloki/iTorch#5]
Mod is working fine for me in single player, but in multiplayer (my server) I'm having issues.

In MP the following happens:

Creative tab for iTorch is empty.
The items show up in JEI, and can be crafted.
When I place the crafted torches, the immediately disappear.  Other people do not see them being held in my hands.

I am on Forge version 2388 - version 1.11.2

**Comment by notloki** [comment]
Changed Block Registry to RegistryEvent
Setup ObjectHolder

**Comment by notloki** [comment]
Pushed to curse.  Please let me know if it fixes your issue.

**Comment by HootlingMC** [comment]
Tested it in MP just now.  Is working.  Thanks!
