### ISSUE TITLE
[1.10.2] Missing language localization 

### ISSUE THREAD

**Issue by MJRLegends** [notloki/iTorch#6]
![](https://i.gyazo.com/8e3488fddd0f1f9a437d23c0178df8ff.png)

**Lang file:** en_US.lang

**I believe the wrong unlocalization name has been used in the lang file** https://github.com/notloki/iTorch/blob/1.10/src/main/resources/assets/itorch/lang/en_US.lang#L17

**Comment by notloki** [comment]
Updated localization to show Creative Tab Group

**Comment by MJRLegends** [comment]
@notloki Thanks :D
