### ISSUE TITLE
1.12 issue

### ISSUE THREAD

**Issue by RayzoRayy** [notloki/iTorch#8]
I wanted to let you know your 1.12.1 version of ITorch doesn't work on 1.12. You need to add
public static final String MC_VERSION = "1.12, 1.12.1"; To your mod, and then also this

acceptedMinecraftVersions = SlurpiesDongles.MC_VERSION... replace Slurpies Dongles with where ever you put the String for MC_VERSION
This should allow your 1.12.1 version to work on 1.12.

**Comment by RayzoRayy** [comment]
Upon looking at your source code, go to your Ref class, and add the line. 
public static final String MC_VERSION = "1.12, 1.12.1";
Next go to your main class Itorch. and change your line from this
@Mod(modid=Ref.MODID, name=Ref.NAME, version=Ref.VERSION, dependencies = Ref.DEPEND) 
To this
@Mod(modid=Ref.MODID, name=Ref.NAME, version=Ref.VERSION, dependencies = Ref.DEPEND, acceptedMinecraftVersions = Ref.MC_VERSION)

This will allow your 1.12.1 to work on 1.12 without needing to worry about maintaining 1.12 and 1.12.1 since no code really changed between the 2. :)

**Comment by notloki** [comment]
Implemented your fix.  Everything is working Thank you.
